//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archivarius.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleCase
    {
        public int Number { get; set; }
        public int CategoryID { get; set; }
        public int CaseNumber { get; set; }
        public System.DateTime Date { get; set; }
        public string ArticleNumber { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Case Case { get; set; }
    }
}
