//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archivarius.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArhivariusEntities1 : DbContext
    {
        public ArhivariusEntities1()
            : base("name=ArhivariusEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Act> Act { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<ArticleCase> ArticleCase { get; set; }
        public virtual DbSet<Case> Case { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Query> Query { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<EnterData> EnterData { get; set; }
    }
}
